ATGAndroidReport.pdf: ATGAndroidReport.tex ATGAndroidReport.bbl section*
	pdflatex ATGAndroidReport.tex
	pdflatex ATGAndroidReport.tex

ATGAndroidReport.bbl: ATGAndroidReport.bib
	biber ATGAndroidReport
